print("        A            RRRRRRR     ")
print("       AAA           RR    RR    ")
print("      AA AA          RR     RR")
print("     AA   AA         RR     RR ")
print("    AA     AA        RR    RR  ")
print("   AA       AA       RRRRRRR  ")
print("  AAAAAAAAAAAAA      RR   RR  ")
print(" AA           AA     RR    RR")
print("AA             AA    RR      RR ")